# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
# https://circleci.com/docs/2.0/browser-testing/#selenium
version: 2
jobs:
  ui-tests:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Running tests
          command: mvn clean test
workflows:
  version: 2
  commit:
    jobs:
      - ui-tests
  periodical:
    triggers:
      - schedule:
          cron: "1 4,8,12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ui-tests